spring:
  profiles:
    active: ser
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

server:
  port: 9001

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wj.funding.admin.model
logging:
  file: demo.log
  level:
    root: warn
